name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore CrudUsuarios.sln
        working-directory: CrudUsuarios

      - name: Build
        run: dotnet build CrudUsuarios.sln --no-restore --configuration Release
        working-directory: CrudUsuarios

      - name: Run tests
        run: dotnet test CrudUsuarios.sln --no-build --configuration Release --logger "trx"
        working-directory: CrudUsuarios
